version: '2'
services:
  web-vitty:
    image: web-vitty
    container_name: web-vitty
    ports:
      - 8001:80
    volumes:
      - /usr/home/spd/woravitp/wwwroot:/usr/share/nginx/html
      - /usr/home/WEBADM/occmnpwl/logs/occmnpweb/api:/logs/web:ro
      - /usr/home/spd/woravitp/logs/adm/api:/logs/adm:ro
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Bangkok
      - TZ=ICT-7
networks:
    default:
       external:
           name: general 
